
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 1094296
 */
public class Gravidade extends javax.swing.JFrame {

    /**
     * Creates new form Gravidade
     */
    public Gravidade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txfPlanetaSelecionado = new javax.swing.JTextField();
        cBPlanetas = new javax.swing.JComboBox<>();
        jbCalcular = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txfPeso = new javax.swing.JTextField();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Gravidade");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Planeta Selecionado; ");

        txfPlanetaSelecionado.setEditable(false);
        txfPlanetaSelecionado.setBackground(new java.awt.Color(255, 255, 255));
        txfPlanetaSelecionado.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        txfPlanetaSelecionado.setForeground(new java.awt.Color(0, 0, 0));
        txfPlanetaSelecionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfPlanetaSelecionadoActionPerformed(evt);
            }
        });

        cBPlanetas.setBackground(new java.awt.Color(255, 255, 255));
        cBPlanetas.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        cBPlanetas.setForeground(new java.awt.Color(0, 0, 0));
        cBPlanetas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mercúrio", "Urano", "Terra", "Vênus", "Marte", "Júpiter", "Saturno", "Netuno", "Lua " }));
        cBPlanetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBPlanetasActionPerformed(evt);
            }
        });

        jbCalcular.setBackground(new java.awt.Color(255, 255, 255));
        jbCalcular.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jbCalcular.setForeground(new java.awt.Color(0, 0, 0));
        jbCalcular.setText("Calcular");
        jbCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCalcularActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Peso na Terra Kg; ");

        txfPeso.setBackground(new java.awt.Color(255, 255, 255));
        txfPeso.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        txfPeso.setForeground(new java.awt.Color(0, 0, 0));
        txfPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfPesoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(txfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txfPlanetaSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                                .addComponent(cBPlanetas, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jbCalcular)))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfPlanetaSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cBPlanetas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jbCalcular)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalcularActionPerformed
try{
    double pesoTerra = Double.parseDouble(txfPeso.getText());
        
       double gravidade = 0;
       
       String planeta = cBPlanetas.getSelectedItem().toString();
               
               switch(planeta) {
            case"Mercúrio":
                gravidade = 3.6;
                break;
                
                case"Vênus":
                gravidade = 8.7;
                break;
                
                case"Terra":
                gravidade = 9.8;
                break;
                
                case"Marte":
                gravidade = 3.7;
                break;
                
                case"Júpiter":
                gravidade = 24.79;
                break;
                
                case"Saturno":
                gravidade = 10.44;
                break;
                
                case"Urano":
                gravidade = 8.69;
                break;
                
                case"Netuno":
                gravidade = 11.15;
                break;
                
                case"Lua":
                gravidade = 1.6;
                break;
            
        }
         //Formula
         double pesoPlaneta = (pesoTerra / 10) * gravidade;
         
         //JOption
         JOptionPane.showMessageDialog(null, "O seu peso em " + planeta +" é: " +String.format("%.2f", pesoPlaneta) +" Kg: ");
        
}catch(NumberFormatException ex){
    JOptionPane.showMessageDialog(null, "Digite um valor Valido!!!");
}
        
    }//GEN-LAST:event_jbCalcularActionPerformed

    private void cBPlanetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBPlanetasActionPerformed

        String Planeta = cBPlanetas.getSelectedItem().toString();
        txfPlanetaSelecionado.setText(Planeta);
        
    }//GEN-LAST:event_cBPlanetasActionPerformed

    private void txfPlanetaSelecionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfPlanetaSelecionadoActionPerformed

    }//GEN-LAST:event_txfPlanetaSelecionadoActionPerformed

    private void txfPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfPesoActionPerformed
       
        txfPeso.getText();
       
    }//GEN-LAST:event_txfPesoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gravidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gravidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gravidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gravidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gravidade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cBPlanetas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbCalcular;
    private javax.swing.JTextField txfPeso;
    private javax.swing.JTextField txfPlanetaSelecionado;
    // End of variables declaration//GEN-END:variables
}
